openapi: 3.0.0
info:
  title: VirusTotal API
  version: "v3"
servers:
  - url: https://www.virustotal.com/api/v3
define: &apikey apikey

paths:
  /ip_addresses/{input_ip}:
   get:
    summary: Get information about an IP address
    operationId: getIpInfo
    parameters:
      - in: path
        name: input_ip
        required: true
        schema:
          type: string
        description: The IP address
    responses:
      '200':
        description: Successful response
        content:
          application/json:
            schema:
              type: object
      '400':
        description: Bad request
      '401':
        description: Unauthorized
      '500':
        description: Internal server error
    security:
      - apiKeyAuth: *apikey

components:
  securitySchemes:
    apiKeyAuth:
      type: apiKey
      in: header
      name: X-Apikey
      description: API key
      x-api-key: *apikey

security:
  - X-Apikey: *apikey
